[package]
name = "imsz"
version = "0.2.0"
authors = [
    "Paulo Scardine <paulo@scardine.com.br>",
    "Mathias Panzenb√∂ck <grosser.meister.morti@gmx.net>"
]
edition = "2021"

[lib]
name = "imsz"
path = "src/lib.rs"

[dev-dependencies]
clap = { version = "3.1.8", features = ["derive"] }
